title: Awsome blog
author: me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is going to be my cool blog site

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
